name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-linux ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Init submodules
      run: |
        git submodule init
        git submodule update

    - name: Build
      run: zig build -Doptimize=ReleaseSafe -Dtarget=${{ matrix.target }}

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: zpz
        path: zig-out/bin/*
